header: |
  /*!
    Knockout Fast Foreach v<%=pkg.version%> (<%=now.toISOString()%>)
    By: Brian M Hunt (C) 2015
    License: MIT
  */
  (function (root, factory) {
    if (typeof define === 'function' && define.amd) {
      define(['knockout'], factory);
    } else if (typeof exports === 'object') {
      module.exports = factory(require('knockout'));
    } else {
      root.KnockoutElse = factory(root.ko);
    }
  }(this, function (ko) {

footer: |
  // Exports
    return {init: init};
  }));

webserver:
  port: 4052
  directoryListing: true
  open: spec/runner.html
  livereload:
    port: 4053

watch:
  index.js
  spec/*
  config.yaml
